package game;

import java.util.List;

import model.Piece;

import data_types.Vector2D;

import javafx.scene.Group;

/**
 * PiecePreview
 * @author Josh Chia
 * 
 * Preview of upcoming Pieces generated by the
 * Random Generator.
 * 
 * Has no direct association with RandomGenerator inorder
 * to improve cohesion.
 *
 */
public class PiecePreview extends Group {
	private Vector2D pos;
	private double width, height;
	private PieceDisplay[] displays;
	
	private final int PREVIEW_SIZE;
	private final int DISPLAY_ROWS = 4;
	private final int DISPLAY_COLS = 4;
	
	/**
	 * Construct a PiecePreview
	 * @param p, position of the preview
	 * @param ps, how far to look ahead
	 * @param w, width in pixels
	 * @param h, height in pixels
	 */
	public PiecePreview(Vector2D p, int ps, double w, double h) {
		pos = p;
		width = w;
		height = h;
		PREVIEW_SIZE = ps;
		
		// Set up the various displays according to preview size
		displays = new PieceDisplay[PREVIEW_SIZE];
		for (int i=0; i<PREVIEW_SIZE; i++) {
			displays[i] = new PieceDisplay(new Vector2D(pos, 0, height*i), width, height, DISPLAY_ROWS, DISPLAY_COLS);
			this.getChildren().add(displays[i]);
		}
	}

	/**
	 * Update the Preview given list of Pieces
	 * @param preview, list of Pieces from Random Generator
	 */
	public void update(List<Piece> preview) {
		for (int i=0; i<PREVIEW_SIZE; i++) {
			displays[i].setDisplay(preview.get(i));
		}
	}
}
